export const MONITORING_DURATION_MS = 30_000;
export const MONITORING_DURATION_SECONDS = MONITORING_DURATION_MS / 1000;
export const TEMP_INTERVAL_MS = 3000;
export const TRAFFIC_INTERVAL_MS = 5000;
export const ACTIVITY_FEED_LIMIT = 10;
export const TEMPERATURE_HISTORY_LIMIT = 20;
